PP_ENV=dev

PP_DBNAME=<PPmysql_dbname>
PP_DBUSER=<PPmysql_user>
PP_DBPASS=<PPmysql_pass>
PP_DBHOST=<PPmysql_host>

PP_DEBUG=1
PP_SAVEQUERIES=1

PP_HOME=<PPlocalurl>
PP_SITEURL=<PPlocalurl>/wp

PP_WP_CACHE=0

PP_DISABLE_WP_CRON=0
PP_DISALLOW_FILE_EDIT=1
PP_AUTO_UPDATE_CORE=0
PP_AUTOMATIC_UPDATER_DISABLED=1